---
- name: Setup Python Dev Environment
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Python3, pip, and venv are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Create a Python virtual environment
      command:
        cmd: python3 -m venv /home/bilal/dev_venv
        creates: /home/bilal/dev_venv/bin/activate

    - name: Install Flask in the virtual environment
      pip:
        name: flask
        virtualenv: /home/bilal/dev_venv
